name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: rohith0210
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_followup: yes

      - name: Commit metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: metrics
